### ISSUE TITLE
[Bug?]Cyborg(and possibly AI) laws

### ISSUE THREAD

**Issue by Zurro13** [HypatiaStation/HypatiaNEW#33]
Description of the Bug:
Cyborg laws are:
1. Safeguard: Protect your assigned space station to the best of your ability. It is not something we can easily afford to replace.
2. Serve: Serve the crew of your assigned space station to the best of your abilities, with priority as according to their rank and role.
3. Protect: Protect the crew of your assigned space station to the best of your abilities, with priority as according to their rank and role.
4. Survive: AI units are not expendable, they are expensive. Do not allow unauthorized personnel to tamper with your equipment.

 What were you doing when the bug happened: started as borg
 What was the expected result of your actions: To see how borgs work on that code.
 What actually happened:Checked laws and seen that law set.
 Reproducibility of the bug (If you were to do the above actions in the exact order that you did them above for 10 times, how many times would the bug reproduce itself:
 Bug Severity (How important is it to fix this bug) [Low, Medium, High, Game Breaking]:Insignificant if it is intended, low if not.

**Comment by uoheinrich** [comment]
Will port over custom lawset. Thanks for bringing this to our attention

**Comment by torger597** [comment]
Fixed in next PR.

**Comment by CrowOfBourbon** [comment]
Will reopen /if/ this isn't fixed.. but I'm damn sure it is.
